import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import 'firebase_options.dart';
import 'providers/auth_provider.dart';
import 'providers/push_provider.dart';
import 'screens/add_server_screen.dart';
import 'screens/overview_screen.dart';
import 'theme.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Try to init Firebase. If it fails (e.g. firebase_options.dart not yet
  // generated by `flutterfire configure`), the app still works — push just
  // doesn't.
  try {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );
  } catch (e) {
    debugPrint('Firebase init failed (push disabled): $e');
  }
  runApp(const ProviderScope(child: WatchlogApp()));
}

class WatchlogApp extends ConsumerStatefulWidget {
  const WatchlogApp({super.key});

  @override
  ConsumerState<WatchlogApp> createState() => _WatchlogAppState();
}

class _WatchlogAppState extends ConsumerState<WatchlogApp> {
  bool _bootstrapped = false;

  @override
  void initState() {
    super.initState();
    _bootstrap();
  }

  Future<void> _bootstrap() async {
    await ref.read(authProvider.notifier).load();
    // Init push (may fail silently if Firebase not configured — that's OK)
    try {
      await ref.read(pushServiceProvider).initialize();
    } catch (e) {
      debugPrint('Push init failed: $e');
    }
    if (mounted) setState(() => _bootstrapped = true);
  }

  @override
  Widget build(BuildContext context) {
    final auth = ref.watch(authProvider);
    return MaterialApp(
      title: 'watchlog',
      debugShowCheckedModeBanner: false,
      theme: buildTheme(),
      home: !_bootstrapped
          ? const _Splash()
          : auth.isAuthenticated
              ? const OverviewScreen()
              : const AddServerScreen(isFirstRun: true),
    );
  }
}

class _Splash extends StatelessWidget {
  const _Splash();
  @override
  Widget build(BuildContext context) {
    return const Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text('👁️', style: TextStyle(fontSize: 64)),
            SizedBox(height: 16),
            CircularProgressIndicator(),
          ],
        ),
      ),
    );
  }
}
